<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>ImageSimilarity</Title>
    <Authors>n1tr3x</Authors>
    <Description>Fast image similarity lib using OpenCV.</Description>
    <Copyright>n1tr3x</Copyright>
    <PackageProjectUrl>https://github.com/n1tr3x/ImageSimilarity</PackageProjectUrl>
    <RepositoryUrl>https://github.com/n1tr3x/ImageSimilarity</RepositoryUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="libcvextern.so" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="libcvextern.so">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Emgu.CV" Version="4.12.0.5764" />
		<PackageReference Include="Emgu.CV.runtime.ubuntu-x64" Version="4.12.0.5764" />
		<PackageReference Include="Emgu.CV.runtime.windows" Version="4.12.0.5764" />
	</ItemGroup>

</Project>
